CREATE TABLE PERSON (
PERSON_ID INTEGER PRIMARY KEY,
NAME TEXT,
SURNAME TEXT,
COM_NAME TEXT,
DESCRIPTION TEXT);

CREATE TABLE ADDRESS (
ADDRESS_ID INTEGER PRIMARY KEY,
PERSON_ID INTEGER,
STREET TEXT,
HOUSE_NO TEXT,
FLAT_NO TEXT,
CITY TEXT,
POST_CODE TEXT,
COUNTRY TEXT,
DESCRIPTION TEXT,
FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID));

CREATE TABLE PHONE (
PHONE_ID INTEGER PRIMARY KEY,
PERSON_ID INTEGER,
NUMBER TEXT NOT NULL,
DESCRIPTION TEXT,
FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID));

CREATE TABLE EMAIL (
EMAIL_ID INTEGER PRIMARY KEY,
PERSON_ID INTEGER,
EMAIL TEXT NOT NULL,
DESCRIPTION TEXT,
FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID));


DROP TABLE ADDRESS;
DROP TABLE PHONE;
DROP TABLE EMAIL;
DROP TABLE PERSON;

