CREATE TABLE PERSON (
PERSON_ID NUMERIC(6) NOT NULL,
NAME VARCHAR(255),
SURNAME VARCHAR(255),
COM_NAME VARCHAR(255),
DESCRIPTION TEXT,
CONSTRAINT PERSON_ID_PK PRIMARY KEY (PERSON_ID));

CREATE SEQUENCE PERSON_SEQ 
INCREMENT BY 1
NO MAXVALUE
MINVALUE 1
START WITH 1
NO CYCLE;

CREATE TABLE ADDRESS (
ADDRESS_ID NUMERIC(6) NOT NULL,
PERSON_ID NUMERIC(6) NOT NULL,
STREET VARCHAR(255),
HOUSE_NO VARCHAR(20),
FLAT_NO VARCHAR(20),
CITY VARCHAR(255),
POST_CODE VARCHAR(20),
COUNTRY VARCHAR(255),
DESCRIPTION TEXT,
CONSTRAINT ADDRESS_ID_PK PRIMARY KEY (ADDRESS_ID),
CONSTRAINT PERSON_ID_FK FOREIGN KEY (PERSON_ID) 
	REFERENCES PERSON(PERSON_ID));

CREATE SEQUENCE ADDRESS_SEQ 
INCREMENT BY 1
NO MAXVALUE
MINVALUE 1
START WITH 1
NO CYCLE;

CREATE TABLE PHONE (
PHONE_ID NUMERIC(6) NOT NULL,
PERSON_ID NUMERIC(6) NOT NULL,
NUMBER VARCHAR(30) NOT NULL,
DESCRIPTION TEXT,
CONSTRAINT PHONE_ID_PK PRIMARY KEY(PHONE_ID),
CONSTRAINT PERSON_ID_FK FOREIGN KEY (PERSON_ID)
	REFERENCES PERSON(PERSON_ID));

CREATE SEQUENCE PHONE_SEQ 
INCREMENT BY 1
NO MAXVALUE
MINVALUE 1
START WITH 1
NO CYCLE;

CREATE TABLE EMAIL (
EMAIL_ID NUMERIC(6) NOT NULL,
PERSON_ID NUMERIC(6) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
DESCRIPTION TEXT,
CONSTRAINT EMAIL_ID_PK PRIMARY KEY (EMAIL_ID),
CONSTRAINT PERSON_ID_FK FOREIGN KEY (PERSON_ID) 
	REFERENCES PERSON(PERSON_ID)
);

CREATE SEQUENCE EMAIL_SEQ 
INCREMENT BY 1
NO MAXVALUE
MINVALUE 1
START WITH 1
NO CYCLE;

DROP TABLE ADDRESS;
DROP TABLE PHONE;
DROP TABLE EMAIL;
DROP TABLE PERSON CASCADE;
DROP SEQUENCE PERSON_SEQ;
DROP SEQUENCE ADDRESS_SEQ;
DROP SEQUENCE PHONE_SEQ;
DROP SEQUENCE EMAIL_SEQ;

